# Generated by Django 3.2.4 on 2021-07-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0002_filesadmin_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesadmin',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
