# Generated by Django 3.2.4 on 2021-07-22 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0005_auto_20210715_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesadmin',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
