# Generated by Django 3.2.4 on 2021-07-24 08:54

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0007_alter_filesadmin_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pop_video_url', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AlterModelOptions(
            name='filesadmin',
            options={'ordering': ['-added_date']},
        ),
    ]
