# Generated by Django 3.2.4 on 2021-07-24 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0008_auto_20210724_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='video_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
    ]
