# Generated by Django 3.2.4 on 2021-08-18 14:22

from django.db import migrations, models
import mywebapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0013_auto_20210725_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('ev_Date', models.DateField()),
                ('ev_Time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, validators=[mywebapp.validators.validate_domainonly_email]),
        ),
    ]
