# Generated by Django 3.2.4 on 2021-08-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0014_auto_20210818_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='ev_location',
            field=models.CharField(default='nairobi', max_length=100),
            preserve_default=False,
        ),
    ]
