# Generated by Django 3.2.4 on 2021-08-18 14:56

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0015_bookings_ev_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('update_image', models.ImageField(upload_to='media/thumbnail')),
                ('update_video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
