# Generated by Django 3.2.4 on 2021-08-18 15:26

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0016_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='updates',
            name='update_image',
            field=models.ImageField(blank=True, upload_to='media/thumbnail'),
        ),
        migrations.AlterField(
            model_name='updates',
            name='update_video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
