# Generated by Django 3.2.4 on 2021-08-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0017_auto_20210818_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('det_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
